name: tinterapp
description: V2 of tINTer

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  web_socket_channel: ^1.1.0
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  # websafe_svg: ^1.1.0
  auto_size_text: ^2.1.0
  flare_flutter: ^2.0.5
  scroll_snap_list: ^0.4.1
  flutter_svg: ^0.18.0
  separated_column: ^1.0.1+2
  keyboard_visibility: ^0.5.6
  property_change_notifier: ^0.2.0
  sliding_up_panel: ^1.0.2
  provider: ^4.3.1
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  bottom_navy_bar: ^5.5.0
  flutter_secure_storage: ^3.3.3
  json_annotation:
  flutter_keyboard_visibility: ^3.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^3.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/profile/
    - assets/discover/
    - assets/splash_screen/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

    - family: OpenSansCondensed
      fonts:
        - asset: assets/fonts/OpenSansCondensed/OpenSansCondensed-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/OpenSansCondensed/OpenSansCondensed-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/OpenSansCondensed/OpenSansCondensed-LightItalic.ttf
          weight: 300
          style: italic

    - family: Podkova
      fonts:
        - asset: assets/fonts/podkova/Podkova-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/podkova/Podkova-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/podkova/Podkova-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/podkova/Podkova-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/podkova/Podkova-ExtraBold.ttf
          weight: 800
          style: normal

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-BoldItalic.ttf
          weight: 700
          style: italic

    - family: SpectralSC
      fonts:
        - asset: assets/fonts/spectral_SC/SpectralSC-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/spectral_SC/SpectralSC-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/spectral_SC/SpectralSC-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/spectral_SC/SpectralSC-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/spectral_SC/SpectralSC-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/spectral_SC/SpectralSC-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/spectral_SC/SpectralSC-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/spectral_SC/SpectralSC-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/spectral_SC/SpectralSC-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/spectral_SC/SpectralSC-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/spectral_SC/SpectralSC-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/spectral_SC/SpectralSC-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/spectral_SC/SpectralSC-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/spectral_SC/SpectralSC-ExtraBoldItalic.ttf
          weight: 800
          style: italic
