name: tinter_backend

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  postgres: ^2.3.2
  meta: ^1.3.0
  json_annotation:
  equatable: ^2.0.0
  dartdap: ^0.6.1
  image:
  built_value: ^8.0.5
  logging: ^1.0.1

  fcm_api:
    path: ../../fcm_api



dev_dependencies:
  build_runner:
  json_serializable: ^4.1.1
  built_value_generator: ^8.0.5