name: tinter_backend

dependencies:
  postgres: ^2.1.1
  meta: ^1.2.2
  json_annotation:
  equatable: ^1.2.3
  dartdap: ^0.4.5
  image:
  built_value: ^7.1.0
  logging: ^0.11.4

  fcm_api:
    path: /home/lulupointu/ProgrammingProjects/fcm_api



dev_dependencies:
  build_runner:
  json_serializable: ^3.3.0
  built_value_generator: ^7.1.0